version: '3.8'
name: simpleshop

services:
  catalogservice:
    build:
      context: .
      dockerfile: src/Services/CatalogService.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoSettings__ConnectionString=mongodb://mongo:27017
      - MongoSettings__DatabaseName=CatalogDb
    depends_on:
      - mongo

  basketservice:
    build:
      context: .
      dockerfile: src/Services/BasketService.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data


volumes:
  mongodbdata:
  redisdata:
